### ISSUE TITLE
ModuleNotFoundError: No module named 'maskrcnn_benchmark'

### ISSUE THREAD

**Issue by Gmonster-24** [djamahl99/findnpropagate#1]
"ModuleNotFoundError: No module named'maskrcnn_benchmark'" appears on line 20 of pcdet/models/preprocessed_detector.py, where self.glip_bboxes = torch.load(self.glip_bbox_file). How can I fix this?

**Comment by Closure-zzy** [comment]
I also encountered this problem, have you solved it? I tried to install maskrcnn_benchmark using torch version 1.10.0, but failed.

**Comment by Closure-zzy** [comment]
I made it! The installation method of maskrcnn_benchmark can be referred to https://github.com/microsoft/GLIP.
Specifically, you can copy the maskrcnn_benchmark folder under the Glip repo to your project and compile it as required.
For me, it works fine with torch version 1.10.0+cu113 and torchvision version 0.11.0+cu113

**Comment by Gmonster-24** [comment]
> Closure

Thanks a lot!
